# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=riscv64 -run-pass=legalizer -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV64I %s
# RUN: llc -march=riscv64 -mattr=+m -run-pass=legalizer -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV64IM %s

--- |

  ; Types < 32 bits exhaustively tested for add only.
  define void @add_i8() { entry: ret void }
  define void @add_i8_signext() { entry: ret void }
  define void @add_i8_zeroext() { entry: ret void }

  define void @add_i16() { entry: ret void }
  define void @add_i16_signext() { entry: ret void }
  define void @add_i16_zeroext() { entry: ret void }

  ; Operations with single word instructions.
  define void @add_i32() { entry: ret void }
  define void @sub_i32() { entry: ret void }
  define void @shl_i32() { entry: ret void }
  define void @ashr_i32() { entry: ret void }
  define void @lshr_i32() { entry: ret void }
  define void @mul_i32() { entry: ret void }
  define void @sdiv_i32() { entry: ret void }
  define void @srem_i32() { entry: ret void }
  define void @udiv_i32() { entry: ret void }
  define void @urem_i32() { entry: ret void }

  ; Operations on XLen types.
  define void @add_i64() { entry: ret void }
  define void @sub_i64() { entry: ret void }
  define void @shl_i64() { entry: ret void }
  define void @ashr_i64() { entry: ret void }
  define void @lshr_i64() { entry: ret void }
  define void @and_i64() { entry: ret void }
  define void @or_i64() { entry: ret void }
  define void @xor_i64() { entry: ret void }
  define void @mul_i64() { entry: ret void }
  define void @sdiv_i64() { entry: ret void }
  define void @srem_i64() { entry: ret void }
  define void @udiv_i64() { entry: ret void }
  define void @urem_i64() { entry: ret void }

  ; Operations on double XLen types which lower to split operations.
  define void @add_i128() { entry: ret void }
  define void @sub_i128() { entry: ret void }
  define void @mul_i128() { entry: ret void }
...
---
name:            add_i8
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i8
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i8
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s8) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s8) = G_TRUNC %3(s64)
    %4:_(s8) = G_ADD %0, %1
    %5:_(s64) = G_ANYEXT %4(s8)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i8_signext
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i8_signext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 56
    ; RV64I: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY4]], [[C]](s64)
    ; RV64I: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; RV64I: $x10 = COPY [[ASHR]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i8_signext
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64IM: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 56
    ; RV64IM: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY4]], [[C]](s64)
    ; RV64IM: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; RV64IM: $x10 = COPY [[ASHR]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s8) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s8) = G_TRUNC %3(s64)
    %4:_(s8) = G_ADD %0, %1
    %5:_(s64) = G_SEXT %4(s8)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i8_zeroext
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i8_zeroext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64I: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64I: $x10 = COPY [[AND]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i8_zeroext
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64IM: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64IM: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64IM: $x10 = COPY [[AND]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s8) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s8) = G_TRUNC %3(s64)
    %4:_(s8) = G_ADD %0, %1
    %5:_(s64) = G_ZEXT %4(s8)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i16
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i16
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s16) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s16) = G_TRUNC %3(s64)
    %4:_(s16) = G_ADD %0, %1
    %5:_(s64) = G_ANYEXT %4(s16)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i16_signext
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i16_signext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 48
    ; RV64I: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY4]], [[C]](s64)
    ; RV64I: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; RV64I: $x10 = COPY [[ASHR]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i16_signext
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64IM: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 48
    ; RV64IM: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY4]], [[C]](s64)
    ; RV64IM: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; RV64IM: $x10 = COPY [[ASHR]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s16) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s16) = G_TRUNC %3(s64)
    %4:_(s16) = G_ADD %0, %1
    %5:_(s64) = G_SEXT %4(s16)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i16_zeroext
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11


    ; RV64I-LABEL: name: add_i16_zeroext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64I: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64I: $x10 = COPY [[AND]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i16_zeroext
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64IM: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; RV64IM: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64IM: $x10 = COPY [[AND]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s16) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s16) = G_TRUNC %3(s64)
    %4:_(s16) = G_ADD %0, %1
    %5:_(s64) = G_ZEXT %4(s16)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADDW:%[0-9]+]]:gpr(s64) = ADDW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADDW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[ADDW:%[0-9]+]]:gpr(s64) = ADDW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ADDW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_ADD %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            sub_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sub_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[SUBW:%[0-9]+]]:gpr(s64) = SUBW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SUBW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: sub_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[SUBW:%[0-9]+]]:gpr(s64) = SUBW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SUBW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_SUB %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            shl_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: shl_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[SLLW:%[0-9]+]]:gpr(s64) = SLLW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SLLW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: shl_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[SLLW:%[0-9]+]]:gpr(s64) = SLLW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SLLW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_SHL %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            ashr_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: ashr_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[SRAW:%[0-9]+]]:gpr(s64) = SRAW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SRAW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: ashr_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[SRAW:%[0-9]+]]:gpr(s64) = SRAW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SRAW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_ASHR %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            lshr_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: lshr_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[SRLW:%[0-9]+]]:gpr(s64) = SRLW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SRLW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: lshr_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[SRLW:%[0-9]+]]:gpr(s64) = SRLW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[SRLW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_LSHR %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            mul_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: mul_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: $x10 = COPY [[COPY2]](s64)
    ; RV64I: $x11 = COPY [[COPY3]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__muldi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY4]](s64)
    ; RV64I: $x10 = COPY [[COPY5]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: mul_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[MULW:%[0-9]+]]:gpr(s64) = MULW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[MULW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_MUL %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            sdiv_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sdiv_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 32
    ; RV64I: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY2]], [[C]](s64)
    ; RV64I: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 32
    ; RV64I: [[SHL1:%[0-9]+]]:_(s64) = G_SHL [[COPY3]], [[C1]](s64)
    ; RV64I: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[SHL1]], [[C1]](s64)
    ; RV64I: $x10 = COPY [[ASHR]](s64)
    ; RV64I: $x11 = COPY [[ASHR1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__divdi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY4]](s64)
    ; RV64I: $x10 = COPY [[COPY5]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: sdiv_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[DIVW:%[0-9]+]]:gpr(s64) = DIVW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[DIVW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_SDIV %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            srem_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: srem_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 32
    ; RV64I: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY2]], [[C]](s64)
    ; RV64I: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 32
    ; RV64I: [[SHL1:%[0-9]+]]:_(s64) = G_SHL [[COPY3]], [[C1]](s64)
    ; RV64I: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[SHL1]], [[C1]](s64)
    ; RV64I: $x10 = COPY [[ASHR]](s64)
    ; RV64I: $x11 = COPY [[ASHR1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__moddi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY4]](s64)
    ; RV64I: $x10 = COPY [[COPY5]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: srem_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[REMW:%[0-9]+]]:gpr(s64) = REMW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[REMW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_SREM %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            udiv_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: udiv_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY2]], [[C]]
    ; RV64I: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY3]], [[C1]]
    ; RV64I: $x10 = COPY [[AND]](s64)
    ; RV64I: $x11 = COPY [[AND1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__udivdi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY4]](s64)
    ; RV64I: $x10 = COPY [[COPY5]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: udiv_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[DIVUW:%[0-9]+]]:gpr(s64) = DIVUW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[DIVUW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_UDIV %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            urem_i32
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: urem_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; RV64I: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY2]], [[C]]
    ; RV64I: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY3]], [[C1]]
    ; RV64I: $x10 = COPY [[AND]](s64)
    ; RV64I: $x11 = COPY [[AND1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__umoddi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY4]](s64)
    ; RV64I: $x10 = COPY [[COPY5]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: urem_i32
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64IM: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64IM: [[REMUW:%[0-9]+]]:gpr(s64) = REMUW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[REMUW]](s64)
    ; RV64IM: $x10 = COPY [[COPY4]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %2:_(s64) = COPY $x10
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $x11
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32) = G_UREM %0, %1
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[ADD]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: add_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[ADD]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_ADD %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            sub_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sub_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SUB]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: sub_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[SUB]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SUB %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            shl_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: shl_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[COPY1]](s64)
    ; RV64I: $x10 = COPY [[SHL]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: shl_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[COPY1]](s64)
    ; RV64IM: $x10 = COPY [[SHL]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SHL %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            ashr_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: ashr_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[COPY]], [[COPY1]](s64)
    ; RV64I: $x10 = COPY [[ASHR]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: ashr_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[COPY]], [[COPY1]](s64)
    ; RV64IM: $x10 = COPY [[ASHR]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_ASHR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            lshr_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: lshr_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[LSHR:%[0-9]+]]:_(s64) = G_LSHR [[COPY]], [[COPY1]](s64)
    ; RV64I: $x10 = COPY [[LSHR]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: lshr_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[LSHR:%[0-9]+]]:_(s64) = G_LSHR [[COPY]], [[COPY1]](s64)
    ; RV64IM: $x10 = COPY [[LSHR]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_LSHR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            and_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: and_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[AND]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: and_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[AND]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_AND %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            or_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: or_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[OR:%[0-9]+]]:_(s64) = G_OR [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[OR]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: or_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[OR:%[0-9]+]]:_(s64) = G_OR [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[OR]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_OR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            xor_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: xor_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[XOR]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: xor_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[XOR]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_XOR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            mul_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: mul_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: $x10 = COPY [[COPY]](s64)
    ; RV64I: $x11 = COPY [[COPY1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__muldi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: $x10 = COPY [[COPY2]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: mul_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[MUL:%[0-9]+]]:_(s64) = G_MUL [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[MUL]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_MUL %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            sdiv_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sdiv_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: $x10 = COPY [[COPY]](s64)
    ; RV64I: $x11 = COPY [[COPY1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__divdi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: $x10 = COPY [[COPY2]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: sdiv_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[SDIV:%[0-9]+]]:_(s64) = G_SDIV [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[SDIV]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SDIV %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            srem_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: srem_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: $x10 = COPY [[COPY]](s64)
    ; RV64I: $x11 = COPY [[COPY1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__moddi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: $x10 = COPY [[COPY2]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: srem_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[SREM:%[0-9]+]]:_(s64) = G_SREM [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[SREM]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SREM %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            udiv_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: udiv_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: $x10 = COPY [[COPY]](s64)
    ; RV64I: $x11 = COPY [[COPY1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__udivdi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: $x10 = COPY [[COPY2]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: udiv_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[UDIV:%[0-9]+]]:_(s64) = G_UDIV [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[UDIV]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_UDIV %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            urem_i64
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: urem_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: $x10 = COPY [[COPY]](s64)
    ; RV64I: $x11 = COPY [[COPY1]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__umoddi3, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: $x10 = COPY [[COPY2]](s64)
    ; RV64I: PseudoRET implicit $x10
    ; RV64IM-LABEL: name: urem_i64
    ; RV64IM: liveins: $x10, $x11
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[UREM:%[0-9]+]]:_(s64) = G_UREM [[COPY]], [[COPY1]]
    ; RV64IM: $x10 = COPY [[UREM]](s64)
    ; RV64IM: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_UREM %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            add_i128
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: add_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY $x13
    ; RV64I: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY2]]
    ; RV64I: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD]](s64), [[COPY2]]
    ; RV64I: [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[COPY1]], [[COPY3]]
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ICMP]](s64)
    ; RV64I: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64I: [[ADD2:%[0-9]+]]:_(s64) = G_ADD [[ADD1]], [[AND]]
    ; RV64I: $x10 = COPY [[ADD]](s64)
    ; RV64I: $x11 = COPY [[ADD2]](s64)
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    ; RV64IM-LABEL: name: add_i128
    ; RV64IM: liveins: $x10, $x11, $x12, $x13
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY $x12
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY $x13
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY2]]
    ; RV64IM: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD]](s64), [[COPY2]]
    ; RV64IM: [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[COPY1]], [[COPY3]]
    ; RV64IM: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ICMP]](s64)
    ; RV64IM: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64IM: [[ADD2:%[0-9]+]]:_(s64) = G_ADD [[ADD1]], [[AND]]
    ; RV64IM: $x10 = COPY [[ADD]](s64)
    ; RV64IM: $x11 = COPY [[ADD2]](s64)
    ; RV64IM: PseudoRET implicit $x10, implicit $x11
    %2:_(s64) = COPY $x10
    %3:_(s64) = COPY $x11
    %4:_(s64) = COPY $x12
    %5:_(s64) = COPY $x13
    %1:_(s128) = G_MERGE_VALUES %4(s64), %5(s64)
    %0:_(s128) = G_MERGE_VALUES %2(s64), %3(s64)
    %6:_(s128) = G_ADD %0, %1
    %7:_(s64), %8:_(s64) = G_UNMERGE_VALUES %6(s128)
    $x10 = COPY %7(s64)
    $x11 = COPY %8(s64)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            sub_i128
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: sub_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY $x13
    ; RV64I: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY2]]
    ; RV64I: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[COPY]](s64), [[COPY2]]
    ; RV64I: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[COPY1]], [[COPY3]]
    ; RV64I: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ICMP]](s64)
    ; RV64I: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64I: [[SUB2:%[0-9]+]]:_(s64) = G_SUB [[SUB1]], [[AND]]
    ; RV64I: $x10 = COPY [[SUB]](s64)
    ; RV64I: $x11 = COPY [[SUB2]](s64)
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    ; RV64IM-LABEL: name: sub_i128
    ; RV64IM: liveins: $x10, $x11, $x12, $x13
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY $x12
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY $x13
    ; RV64IM: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY2]]
    ; RV64IM: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[COPY]](s64), [[COPY2]]
    ; RV64IM: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[COPY1]], [[COPY3]]
    ; RV64IM: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; RV64IM: [[COPY4:%[0-9]+]]:_(s64) = COPY [[ICMP]](s64)
    ; RV64IM: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY4]], [[C]]
    ; RV64IM: [[SUB2:%[0-9]+]]:_(s64) = G_SUB [[SUB1]], [[AND]]
    ; RV64IM: $x10 = COPY [[SUB]](s64)
    ; RV64IM: $x11 = COPY [[SUB2]](s64)
    ; RV64IM: PseudoRET implicit $x10, implicit $x11
    %2:_(s64) = COPY $x10
    %3:_(s64) = COPY $x11
    %4:_(s64) = COPY $x12
    %5:_(s64) = COPY $x13
    %1:_(s128) = G_MERGE_VALUES %4(s64), %5(s64)
    %0:_(s128) = G_MERGE_VALUES %2(s64), %3(s64)
    %6:_(s128) = G_SUB %0, %1
    %7:_(s64), %8:_(s64) = G_UNMERGE_VALUES %6(s128)
    $x10 = COPY %7(s64)
    $x11 = COPY %8(s64)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            mul_i128
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: mul_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:_(s64) = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:_(s64) = COPY $x13
    ; RV64I: $x10 = COPY [[COPY]](s64)
    ; RV64I: $x11 = COPY [[COPY1]](s64)
    ; RV64I: $x12 = COPY [[COPY2]](s64)
    ; RV64I: $x13 = COPY [[COPY3]](s64)
    ; RV64I: PseudoCALL target-flags(riscv-call) &__multi3, implicit-def $x1, implicit $x10, implicit $x11, implicit $x12, implicit $x13, implicit-def $x10, implicit-def $x11
    ; RV64I: [[COPY4:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64I: [[COPY5:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: $x11 = COPY [[COPY5]](s64)
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    ; RV64IM-LABEL: name: mul_i128
    ; RV64IM: liveins: $x10, $x11, $x12, $x13
    ; RV64IM: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; RV64IM: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; RV64IM: [[COPY2:%[0-9]+]]:_(s64) = COPY $x12
    ; RV64IM: [[COPY3:%[0-9]+]]:_(s64) = COPY $x13
    ; RV64IM: [[MUL:%[0-9]+]]:_(s64) = G_MUL [[COPY]], [[COPY2]]
    ; RV64IM: [[MUL1:%[0-9]+]]:_(s64) = G_MUL [[COPY1]], [[COPY2]]
    ; RV64IM: [[MUL2:%[0-9]+]]:_(s64) = G_MUL [[COPY]], [[COPY3]]
    ; RV64IM: [[UMULH:%[0-9]+]]:_(s64) = G_UMULH [[COPY]], [[COPY2]]
    ; RV64IM: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[MUL1]], [[MUL2]]
    ; RV64IM: [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[ADD]], [[UMULH]]
    ; RV64IM: $x10 = COPY [[MUL]](s64)
    ; RV64IM: $x11 = COPY [[ADD1]](s64)
    ; RV64IM: PseudoRET implicit $x10, implicit $x11
    %2:_(s64) = COPY $x10
    %3:_(s64) = COPY $x11
    %4:_(s64) = COPY $x12
    %5:_(s64) = COPY $x13
    %1:_(s128) = G_MERGE_VALUES %4(s64), %5(s64)
    %0:_(s128) = G_MERGE_VALUES %2(s64), %3(s64)
    %6:_(s128) = G_MUL %0, %1
    %7:_(s64), %8:_(s64) = G_UNMERGE_VALUES %6(s128)
    $x10 = COPY %7(s64)
    $x11 = COPY %8(s64)
    PseudoRET implicit $x10, implicit $x11

...
