# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=riscv32 -run-pass=instruction-select -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV32I %s

--- |

  define void @add_anyext() { entry: ret void }
  define void @add_i8_signext() { entry: ret void }
  define void @add_i8_zeroext() { entry: ret void }
  define void @add_i16_signext() { entry: ret void }
  define void @add_i16_zeroext() { entry: ret void }

  define void @add_i32() { entry: ret void }
  define void @sub_i32() { entry: ret void }
  define void @shl_i32() { entry: ret void }
  define void @ashr_i32() { entry: ret void }
  define void @lshr_i32() { entry: ret void }
  define void @and_i32() { entry: ret void }
  define void @or_i32() { entry: ret void }
  define void @xor_i32() { entry: ret void }

  ; Split operations.
  define void @add_i64() { entry: ret void }
  define void @sub_i64() { entry: ret void }
...
---
name:            add_anyext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_anyext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[ADD]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %2:gprb(s32) = COPY $x11
    %6:gprb(s32) = COPY %0(s32)
    %7:gprb(s32) = COPY %2(s32)
    %8:gprb(s32) = G_ADD %6, %7
    %5:gprb(s32) = COPY %8(s32)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_i8_signext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_i8_signext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV32I: [[SLLI:%[0-9]+]]:gpr = SLLI [[ADD]], 24
    ; RV32I: [[SRAI:%[0-9]+]]:gpr = SRAI [[SLLI]], 24
    ; RV32I: $x10 = COPY [[SRAI]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %2:gprb(s32) = COPY $x11
    %6:gprb(s32) = COPY %0(s32)
    %7:gprb(s32) = COPY %2(s32)
    %8:gprb(s32) = G_ADD %6, %7
    %9:gprb(s32) = COPY %8(s32)
    %11:gprb(s32) = G_CONSTANT i32 24
    %10:gprb(s32) = G_SHL %9, %11(s32)
    %5:gprb(s32) = G_ASHR %10, %11(s32)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_i8_zeroext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_i8_zeroext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV32I: [[ANDI:%[0-9]+]]:gpr = ANDI [[ADD]], 255
    ; RV32I: $x10 = COPY [[ANDI]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %2:gprb(s32) = COPY $x11
    %6:gprb(s32) = COPY %0(s32)
    %7:gprb(s32) = COPY %2(s32)
    %8:gprb(s32) = G_ADD %6, %7
    %9:gprb(s32) = G_CONSTANT i32 255
    %10:gprb(s32) = COPY %8(s32)
    %5:gprb(s32) = G_AND %10, %9
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_i16_signext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_i16_signext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV32I: [[SLLI:%[0-9]+]]:gpr = SLLI [[ADD]], 16
    ; RV32I: [[SRAI:%[0-9]+]]:gpr = SRAI [[SLLI]], 16
    ; RV32I: $x10 = COPY [[SRAI]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %2:gprb(s32) = COPY $x11
    %6:gprb(s32) = COPY %0(s32)
    %7:gprb(s32) = COPY %2(s32)
    %8:gprb(s32) = G_ADD %6, %7
    %9:gprb(s32) = COPY %8(s32)
    %11:gprb(s32) = G_CONSTANT i32 16
    %10:gprb(s32) = G_SHL %9, %11(s32)
    %5:gprb(s32) = G_ASHR %10, %11(s32)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_i16_zeroext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_i16_zeroext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV32I: [[LUI:%[0-9]+]]:gpr = LUI 16
    ; RV32I: [[ADDI:%[0-9]+]]:gpr = ADDI [[LUI]], -1
    ; RV32I: [[AND:%[0-9]+]]:gpr = AND [[ADD]], [[ADDI]]
    ; RV32I: $x10 = COPY [[AND]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %2:gprb(s32) = COPY $x11
    %6:gprb(s32) = COPY %0(s32)
    %7:gprb(s32) = COPY %2(s32)
    %8:gprb(s32) = G_ADD %6, %7
    %9:gprb(s32) = G_CONSTANT i32 65535
    %10:gprb(s32) = COPY %8(s32)
    %5:gprb(s32) = G_AND %10, %9
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[ADD]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ADD %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            sub_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: sub_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[SUB]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_SUB %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            shl_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: shl_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[SLL:%[0-9]+]]:gpr = SLL [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[SLL]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_SHL %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            ashr_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: ashr_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[SRA:%[0-9]+]]:gpr = SRA [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[SRA]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ASHR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            lshr_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: lshr_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[SRL:%[0-9]+]]:gpr = SRL [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[SRL]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_LSHR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            and_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: and_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[AND:%[0-9]+]]:gpr = AND [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[AND]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_AND %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            or_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: or_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[OR:%[0-9]+]]:gpr = OR [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[OR]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_OR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            xor_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: xor_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[XOR:%[0-9]+]]:gpr = XOR [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[XOR]]
    ; RV32I: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_XOR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            add_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV32I-LABEL: name: add_i64
    ; RV32I: liveins: $x10, $x11, $x12, $x13
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gpr = COPY $x12
    ; RV32I: [[COPY3:%[0-9]+]]:gpr = COPY $x13
    ; RV32I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY2]]
    ; RV32I: [[SLTU:%[0-9]+]]:gpr = SLTU [[ADD]], [[COPY2]]
    ; RV32I: [[ADD1:%[0-9]+]]:gpr = ADD [[COPY1]], [[COPY3]]
    ; RV32I: [[ANDI:%[0-9]+]]:gpr = ANDI [[SLTU]], 1
    ; RV32I: [[ADD2:%[0-9]+]]:gpr = ADD [[ADD1]], [[ANDI]]
    ; RV32I: $x10 = COPY [[ADD]]
    ; RV32I: $x11 = COPY [[ADD2]]
    ; RV32I: PseudoRET implicit $x10, implicit $x11
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = COPY $x12
    %3:gprb(s32) = COPY $x13
    %13:gprb(s32) = G_ADD %0, %2
    %19:gprb(s32) = G_ICMP intpred(ult), %13(s32), %2
    %17:gprb(s32) = G_ADD %1, %3
    %20:gprb(s32) = G_CONSTANT i32 1
    %21:gprb(s32) = COPY %19(s32)
    %18:gprb(s32) = G_AND %21, %20
    %15:gprb(s32) = G_ADD %17, %18
    $x10 = COPY %13(s32)
    $x11 = COPY %15(s32)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            sub_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV32I-LABEL: name: sub_i64
    ; RV32I: liveins: $x10, $x11, $x12, $x13
    ; RV32I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gpr = COPY $x12
    ; RV32I: [[COPY3:%[0-9]+]]:gpr = COPY $x13
    ; RV32I: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY2]]
    ; RV32I: [[SLTU:%[0-9]+]]:gpr = SLTU [[COPY]], [[COPY2]]
    ; RV32I: [[SUB1:%[0-9]+]]:gpr = SUB [[COPY1]], [[COPY3]]
    ; RV32I: [[ANDI:%[0-9]+]]:gpr = ANDI [[SLTU]], 1
    ; RV32I: [[SUB2:%[0-9]+]]:gpr = SUB [[SUB1]], [[ANDI]]
    ; RV32I: $x10 = COPY [[SUB]]
    ; RV32I: $x11 = COPY [[SUB2]]
    ; RV32I: PseudoRET implicit $x10, implicit $x11
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = COPY $x12
    %3:gprb(s32) = COPY $x13
    %13:gprb(s32) = G_SUB %0, %2
    %21:gprb(s32) = G_ICMP intpred(ult), %0(s32), %2
    %17:gprb(s32) = G_SUB %1, %3
    %22:gprb(s32) = G_CONSTANT i32 1
    %23:gprb(s32) = COPY %21(s32)
    %18:gprb(s32) = G_AND %23, %22
    %15:gprb(s32) = G_SUB %17, %18
    $x10 = COPY %13(s32)
    $x11 = COPY %15(s32)
    PseudoRET implicit $x10, implicit $x11

...
