# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=riscv64 -run-pass=instruction-select -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV64I %s

--- |

  define void @add_anyext() { entry: ret void }
  define void @add_i8_signext() { entry: ret void }
  define void @add_i8_zeroext() { entry: ret void }
  define void @add_i16_signext() { entry: ret void }
  define void @add_i16_zeroext() { entry: ret void }

  ; Special case for i32 - single word operations are used.
  define void @add_i32() { entry: ret void }
  define void @sub_i32() { entry: ret void }
  define void @shl_i32() { entry: ret void }
  define void @ashr_i32() { entry: ret void }
  define void @lshr_i32() { entry: ret void }

  define void @add_i64() { entry: ret void }
  define void @sub_i64() { entry: ret void }
  define void @shl_i64() { entry: ret void }
  define void @ashr_i64() { entry: ret void }
  define void @lshr_i64() { entry: ret void }
  define void @and_i64() { entry: ret void }
  define void @or_i64() { entry: ret void }
  define void @xor_i64() { entry: ret void }

  ; Split operations.
  define void @add_i128() { entry: ret void }
  define void @sub_i128() { entry: ret void }
...
---
name:            add_anyext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_anyext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[ADD]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gprb(s64) = COPY %0(s64)
    %7:gprb(s64) = COPY %2(s64)
    %8:gprb(s64) = G_ADD %6, %7
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i8_signext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i8_signext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV64I: [[SLLI:%[0-9]+]]:gpr = SLLI [[ADD]], 56
    ; RV64I: [[SRAI:%[0-9]+]]:gpr = SRAI [[SLLI]], 56
    ; RV64I: $x10 = COPY [[SRAI]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gprb(s64) = COPY %0(s64)
    %7:gprb(s64) = COPY %2(s64)
    %8:gprb(s64) = G_ADD %6, %7
    %9:gprb(s64) = COPY %8(s64)
    %11:gprb(s64) = G_CONSTANT i64 56
    %10:gprb(s64) = G_SHL %9, %11(s64)
    %5:gprb(s64) = G_ASHR %10, %11(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i8_zeroext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i8_zeroext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV64I: [[ANDI:%[0-9]+]]:gpr = ANDI [[ADD]], 255
    ; RV64I: $x10 = COPY [[ANDI]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gprb(s64) = COPY %0(s64)
    %7:gprb(s64) = COPY %2(s64)
    %8:gprb(s64) = G_ADD %6, %7
    %9:gprb(s64) = G_CONSTANT i64 255
    %10:gprb(s64) = COPY %8(s64)
    %5:gprb(s64) = G_AND %10, %9
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i16_signext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i16_signext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV64I: [[SLLI:%[0-9]+]]:gpr = SLLI [[ADD]], 48
    ; RV64I: [[SRAI:%[0-9]+]]:gpr = SRAI [[SLLI]], 48
    ; RV64I: $x10 = COPY [[SRAI]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gprb(s64) = COPY %0(s64)
    %7:gprb(s64) = COPY %2(s64)
    %8:gprb(s64) = G_ADD %6, %7
    %9:gprb(s64) = COPY %8(s64)
    %11:gprb(s64) = G_CONSTANT i64 48
    %10:gprb(s64) = G_SHL %9, %11(s64)
    %5:gprb(s64) = G_ASHR %10, %11(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i16_zeroext
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i16_zeroext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV64I: [[LUI:%[0-9]+]]:gpr = LUI 16
    ; RV64I: [[ADDIW:%[0-9]+]]:gpr = ADDIW [[LUI]], -1
    ; RV64I: [[AND:%[0-9]+]]:gpr = AND [[ADD]], [[ADDIW]]
    ; RV64I: $x10 = COPY [[AND]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gprb(s64) = COPY %0(s64)
    %7:gprb(s64) = COPY %2(s64)
    %8:gprb(s64) = G_ADD %6, %7
    %9:gprb(s64) = G_CONSTANT i64 65535
    %10:gprb(s64) = COPY %8(s64)
    %5:gprb(s64) = G_AND %10, %9
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[ADDW:%[0-9]+]]:gpr = ADDW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[ADDW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = ADDW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            sub_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sub_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SUBW:%[0-9]+]]:gpr = SUBW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SUBW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = SUBW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            shl_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: shl_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SLLW:%[0-9]+]]:gpr = SLLW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SLLW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = SLLW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            ashr_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: ashr_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SRAW:%[0-9]+]]:gpr = SRAW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SRAW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = SRAW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            lshr_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: lshr_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SRLW:%[0-9]+]]:gpr = SRLW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SRLW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = SRLW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[ADD]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_ADD %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            sub_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sub_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SUB]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_SUB %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            shl_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: shl_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SLL:%[0-9]+]]:gpr = SLL [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SLL]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_SHL %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            ashr_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: ashr_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SRA:%[0-9]+]]:gpr = SRA [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SRA]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_ASHR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            lshr_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: lshr_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[SRL:%[0-9]+]]:gpr = SRL [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SRL]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_LSHR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            and_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: and_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[AND:%[0-9]+]]:gpr = AND [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[AND]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_AND %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            or_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: or_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[OR:%[0-9]+]]:gpr = OR [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[OR]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_OR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            xor_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: xor_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[XOR:%[0-9]+]]:gpr = XOR [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[XOR]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_XOR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            add_i128
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: add_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:gpr = COPY $x13
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY2]]
    ; RV64I: [[SLTU:%[0-9]+]]:gpr = SLTU [[ADD]], [[COPY2]]
    ; RV64I: [[ADD1:%[0-9]+]]:gpr = ADD [[COPY1]], [[COPY3]]
    ; RV64I: [[ANDI:%[0-9]+]]:gpr = ANDI [[SLTU]], 1
    ; RV64I: [[ADD2:%[0-9]+]]:gpr = ADD [[ADD1]], [[ANDI]]
    ; RV64I: $x10 = COPY [[ADD]]
    ; RV64I: $x11 = COPY [[ADD2]]
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = COPY $x12
    %3:gprb(s64) = COPY $x13
    %13:gprb(s64) = G_ADD %0, %2
    %19:gprb(s64) = G_ICMP intpred(ult), %13(s64), %2
    %17:gprb(s64) = G_ADD %1, %3
    %20:gprb(s64) = G_CONSTANT i64 1
    %21:gprb(s64) = COPY %19(s64)
    %18:gprb(s64) = G_AND %21, %20
    %15:gprb(s64) = G_ADD %17, %18
    $x10 = COPY %13(s64)
    $x11 = COPY %15(s64)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            sub_i128
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: sub_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:gpr = COPY $x13
    ; RV64I: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY2]]
    ; RV64I: [[SLTU:%[0-9]+]]:gpr = SLTU [[COPY]], [[COPY2]]
    ; RV64I: [[SUB1:%[0-9]+]]:gpr = SUB [[COPY1]], [[COPY3]]
    ; RV64I: [[ANDI:%[0-9]+]]:gpr = ANDI [[SLTU]], 1
    ; RV64I: [[SUB2:%[0-9]+]]:gpr = SUB [[SUB1]], [[ANDI]]
    ; RV64I: $x10 = COPY [[SUB]]
    ; RV64I: $x11 = COPY [[SUB2]]
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = COPY $x12
    %3:gprb(s64) = COPY $x13
    %13:gprb(s64) = G_SUB %0, %2
    %21:gprb(s64) = G_ICMP intpred(ult), %0(s64), %2
    %17:gprb(s64) = G_SUB %1, %3
    %22:gprb(s64) = G_CONSTANT i64 1
    %23:gprb(s64) = COPY %21(s64)
    %18:gprb(s64) = G_AND %23, %22
    %15:gprb(s64) = G_SUB %17, %18
    $x10 = COPY %13(s64)
    $x11 = COPY %15(s64)
    PseudoRET implicit $x10, implicit $x11

...
