# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=riscv64 -mattr=+m -run-pass=instruction-select -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV64I %s

--- |

  ; Special case for i32 - single word operations are used.
  define void @mul_i32() { entry: ret void }
  define void @sdiv_i32() { entry: ret void }
  define void @srem_i32() { entry: ret void }
  define void @udiv_i32() { entry: ret void }
  define void @urem_i32() { entry: ret void }

  define void @mul_i64() { entry: ret void }
  define void @sdiv_i64() { entry: ret void }
  define void @srem_i64() { entry: ret void }
  define void @udiv_i64() { entry: ret void }
  define void @urem_i64() { entry: ret void }

  ; Split operations.
  define void @mul_i128() { entry: ret void }
...
---
name:            mul_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: mul_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[MULW:%[0-9]+]]:gpr = MULW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[MULW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = MULW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            sdiv_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sdiv_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[DIVW:%[0-9]+]]:gpr = DIVW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[DIVW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = DIVW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            srem_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: srem_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[REMW:%[0-9]+]]:gpr = REMW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[REMW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = REMW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            udiv_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: udiv_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[DIVUW:%[0-9]+]]:gpr = DIVUW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[DIVUW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = DIVUW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            urem_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: urem_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[REMUW:%[0-9]+]]:gpr = REMUW [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[REMUW]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %2:gprb(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = REMUW %6(s64), %7(s64)
    %5:gprb(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            mul_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: mul_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[MUL:%[0-9]+]]:gpr = MUL [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[MUL]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_MUL %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            sdiv_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sdiv_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[DIV:%[0-9]+]]:gpr = DIV [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[DIV]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_SDIV %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            srem_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: srem_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[REM:%[0-9]+]]:gpr = REM [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[REM]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_SREM %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            udiv_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: udiv_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[DIVU:%[0-9]+]]:gpr = DIVU [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[DIVU]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_UDIV %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            urem_i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: urem_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[REMU:%[0-9]+]]:gpr = REMU [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[REMU]]
    ; RV64I: PseudoRET implicit $x10
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = G_UREM %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            mul_i128
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: mul_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:gpr = COPY $x13
    ; RV64I: [[MUL:%[0-9]+]]:gpr = MUL [[COPY]], [[COPY2]]
    ; RV64I: [[MUL1:%[0-9]+]]:gpr = MUL [[COPY1]], [[COPY2]]
    ; RV64I: [[MUL2:%[0-9]+]]:gpr = MUL [[COPY]], [[COPY3]]
    ; RV64I: [[MULHU:%[0-9]+]]:gpr = MULHU [[COPY]], [[COPY2]]
    ; RV64I: [[ADD:%[0-9]+]]:gpr = ADD [[MUL1]], [[MUL2]]
    ; RV64I: [[ADD1:%[0-9]+]]:gpr = ADD [[ADD]], [[MULHU]]
    ; RV64I: $x10 = COPY [[MUL]]
    ; RV64I: $x11 = COPY [[ADD1]]
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    %0:gprb(s64) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(s64) = COPY $x12
    %3:gprb(s64) = COPY $x13
    %13:gprb(s64) = G_MUL %0, %2
    %14:gprb(s64) = G_MUL %1, %2
    %15:gprb(s64) = G_MUL %0, %3
    %16:gprb(s64) = G_UMULH %0, %2
    %17:gprb(s64) = G_ADD %14, %15
    %18:gprb(s64) = G_ADD %17, %16
    $x10 = COPY %13(s64)
    $x11 = COPY %18(s64)
    PseudoRET implicit $x10, implicit $x11

...
