# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=riscv32 -run-pass=regbankselect -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV32I %s

--- |

  define void @add_anyext() { entry: ret void }
  define void @add_signext() { entry: ret void }
  define void @add_zeroext() { entry: ret void }

  define void @add_i32() { entry: ret void }
  define void @sub_i32() { entry: ret void }
  define void @shl_i32() { entry: ret void }
  define void @ashr_i32() { entry: ret void }
  define void @lshr_i32() { entry: ret void }
  define void @and_i32() { entry: ret void }
  define void @or_i32() { entry: ret void }
  define void @xor_i32() { entry: ret void }
  define void @mul_i32() { entry: ret void }
  define void @sdiv_i32() { entry: ret void }
  define void @srem_i32() { entry: ret void }
  define void @udiv_i32() { entry: ret void }
  define void @urem_i32() { entry: ret void }

  ; Split operations.
  define void @add_i64() { entry: ret void }
  define void @sub_i64() { entry: ret void }
  define void @mul_i64() { entry: ret void }
...
---
name:            add_anyext
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_anyext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gprb(s32) = COPY [[COPY]](s32)
    ; RV32I: [[COPY3:%[0-9]+]]:gprb(s32) = COPY [[COPY1]](s32)
    ; RV32I: [[ADD:%[0-9]+]]:gprb(s32) = G_ADD [[COPY2]], [[COPY3]]
    ; RV32I: [[COPY4:%[0-9]+]]:gprb(s32) = COPY [[ADD]](s32)
    ; RV32I: $x10 = COPY [[COPY4]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %6:_(s32) = COPY %0(s32)
    %7:_(s32) = COPY %2(s32)
    %8:_(s32) = G_ADD %6, %7
    %5:_(s32) = COPY %8(s32)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_signext
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_signext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gprb(s32) = COPY [[COPY]](s32)
    ; RV32I: [[COPY3:%[0-9]+]]:gprb(s32) = COPY [[COPY1]](s32)
    ; RV32I: [[ADD:%[0-9]+]]:gprb(s32) = G_ADD [[COPY2]], [[COPY3]]
    ; RV32I: [[COPY4:%[0-9]+]]:gprb(s32) = COPY [[ADD]](s32)
    ; RV32I: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 24
    ; RV32I: [[SHL:%[0-9]+]]:gprb(s32) = G_SHL [[COPY4]], [[C]](s32)
    ; RV32I: [[ASHR:%[0-9]+]]:gprb(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; RV32I: $x10 = COPY [[ASHR]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %6:_(s32) = COPY %0(s32)
    %7:_(s32) = COPY %2(s32)
    %8:_(s32) = G_ADD %6, %7
    %9:_(s32) = COPY %8(s32)
    %11:_(s32) = G_CONSTANT i32 24
    %10:_(s32) = G_SHL %9, %11(s32)
    %5:_(s32) = G_ASHR %10, %11(s32)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_zeroext
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_zeroext
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gprb(s32) = COPY [[COPY]](s32)
    ; RV32I: [[COPY3:%[0-9]+]]:gprb(s32) = COPY [[COPY1]](s32)
    ; RV32I: [[ADD:%[0-9]+]]:gprb(s32) = G_ADD [[COPY2]], [[COPY3]]
    ; RV32I: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 255
    ; RV32I: [[COPY4:%[0-9]+]]:gprb(s32) = COPY [[ADD]](s32)
    ; RV32I: [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY4]], [[C]]
    ; RV32I: $x10 = COPY [[AND]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %6:_(s32) = COPY %0(s32)
    %7:_(s32) = COPY %2(s32)
    %8:_(s32) = G_ADD %6, %7
    %9:_(s32) = G_CONSTANT i32 255
    %10:_(s32) = COPY %8(s32)
    %5:_(s32) = G_AND %10, %9
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            add_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: add_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[ADD:%[0-9]+]]:gprb(s32) = G_ADD [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[ADD]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_ADD %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            sub_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: sub_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[SUB]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_SUB %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            shl_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: shl_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[SHL:%[0-9]+]]:gprb(s32) = G_SHL [[COPY]], [[COPY1]](s32)
    ; RV32I: $x10 = COPY [[SHL]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_SHL %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            ashr_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: ashr_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[ASHR:%[0-9]+]]:gprb(s32) = G_ASHR [[COPY]], [[COPY1]](s32)
    ; RV32I: $x10 = COPY [[ASHR]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_ASHR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            lshr_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: lshr_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[LSHR:%[0-9]+]]:gprb(s32) = G_LSHR [[COPY]], [[COPY1]](s32)
    ; RV32I: $x10 = COPY [[LSHR]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_LSHR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            and_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: and_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[AND]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_AND %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            or_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: or_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[OR]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_OR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            xor_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: xor_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[XOR:%[0-9]+]]:gprb(s32) = G_XOR [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[XOR]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_XOR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            mul_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: mul_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[MUL:%[0-9]+]]:gprb(s32) = G_MUL [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[MUL]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_MUL %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            sdiv_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: sdiv_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[SDIV:%[0-9]+]]:gprb(s32) = G_SDIV [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[SDIV]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_SDIV %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            srem_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: srem_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[SREM:%[0-9]+]]:gprb(s32) = G_SREM [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[SREM]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_SREM %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            udiv_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: udiv_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[UDIV:%[0-9]+]]:gprb(s32) = G_UDIV [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[UDIV]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_UDIV %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            urem_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: urem_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[UREM:%[0-9]+]]:gprb(s32) = G_UREM [[COPY]], [[COPY1]]
    ; RV32I: $x10 = COPY [[UREM]](s32)
    ; RV32I: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_UREM %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            add_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV32I-LABEL: name: add_i64
    ; RV32I: liveins: $x10, $x11, $x12, $x13
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x12
    ; RV32I: [[COPY3:%[0-9]+]]:gprb(s32) = COPY $x13
    ; RV32I: [[ADD:%[0-9]+]]:gprb(s32) = G_ADD [[COPY]], [[COPY2]]
    ; RV32I: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[ADD]](s32), [[COPY2]]
    ; RV32I: [[ADD1:%[0-9]+]]:gprb(s32) = G_ADD [[COPY1]], [[COPY3]]
    ; RV32I: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I: [[COPY4:%[0-9]+]]:gprb(s32) = COPY [[ICMP]](s32)
    ; RV32I: [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY4]], [[C]]
    ; RV32I: [[ADD2:%[0-9]+]]:gprb(s32) = G_ADD [[ADD1]], [[AND]]
    ; RV32I: $x10 = COPY [[ADD]](s32)
    ; RV32I: $x11 = COPY [[ADD2]](s32)
    ; RV32I: PseudoRET implicit $x10, implicit $x11
    %2:_(s32) = COPY $x10
    %3:_(s32) = COPY $x11
    %4:_(s32) = COPY $x12
    %5:_(s32) = COPY $x13
    %13:_(s32) = G_ADD %2, %4
    %19:_(s32) = G_ICMP intpred(ult), %13(s32), %4
    %17:_(s32) = G_ADD %3, %5
    %20:_(s32) = G_CONSTANT i32 1
    %21:_(s32) = COPY %19(s32)
    %18:_(s32) = G_AND %21, %20
    %15:_(s32) = G_ADD %17, %18
    $x10 = COPY %13(s32)
    $x11 = COPY %15(s32)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            sub_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV32I-LABEL: name: sub_i64
    ; RV32I: liveins: $x10, $x11, $x12, $x13
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x12
    ; RV32I: [[COPY3:%[0-9]+]]:gprb(s32) = COPY $x13
    ; RV32I: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[COPY]], [[COPY2]]
    ; RV32I: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[COPY]](s32), [[COPY2]]
    ; RV32I: [[SUB1:%[0-9]+]]:gprb(s32) = G_SUB [[COPY1]], [[COPY3]]
    ; RV32I: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I: [[COPY4:%[0-9]+]]:gprb(s32) = COPY [[ICMP]](s32)
    ; RV32I: [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY4]], [[C]]
    ; RV32I: [[SUB2:%[0-9]+]]:gprb(s32) = G_SUB [[SUB1]], [[AND]]
    ; RV32I: $x10 = COPY [[SUB]](s32)
    ; RV32I: $x11 = COPY [[SUB2]](s32)
    ; RV32I: PseudoRET implicit $x10, implicit $x11
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = COPY $x12
    %3:_(s32) = COPY $x13
    %13:_(s32) = G_SUB %0, %2
    %21:_(s32) = G_ICMP intpred(ult), %0(s32), %2
    %17:_(s32) = G_SUB %1, %3
    %22:_(s32) = G_CONSTANT i32 1
    %23:_(s32) = COPY %21(s32)
    %18:_(s32) = G_AND %23, %22
    %15:_(s32) = G_SUB %17, %18
    $x10 = COPY %13(s32)
    $x11 = COPY %15(s32)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            mul_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV32I-LABEL: name: mul_i64
    ; RV32I: liveins: $x10, $x11, $x12, $x13
    ; RV32I: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x12
    ; RV32I: [[COPY3:%[0-9]+]]:gprb(s32) = COPY $x13
    ; RV32I: [[MUL:%[0-9]+]]:gprb(s32) = G_MUL [[COPY]], [[COPY2]]
    ; RV32I: [[MUL1:%[0-9]+]]:gprb(s32) = G_MUL [[COPY1]], [[COPY2]]
    ; RV32I: [[MUL2:%[0-9]+]]:gprb(s32) = G_MUL [[COPY]], [[COPY3]]
    ; RV32I: [[UMULH:%[0-9]+]]:gprb(s32) = G_UMULH [[COPY]], [[COPY2]]
    ; RV32I: [[ADD:%[0-9]+]]:gprb(s32) = G_ADD [[MUL1]], [[MUL2]]
    ; RV32I: [[ADD1:%[0-9]+]]:gprb(s32) = G_ADD [[ADD]], [[UMULH]]
    ; RV32I: $x10 = COPY [[MUL]](s32)
    ; RV32I: $x11 = COPY [[ADD1]](s32)
    ; RV32I: PseudoRET implicit $x10, implicit $x11
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = COPY $x12
    %3:_(s32) = COPY $x13
    %13:_(s32) = G_MUL %0, %2
    %14:_(s32) = G_MUL %1, %2
    %15:_(s32) = G_MUL %0, %3
    %16:_(s32) = G_UMULH %0, %2
    %17:_(s32) = G_ADD %14, %15
    %18:_(s32) = G_ADD %17, %16
    $x10 = COPY %13(s32)
    $x11 = COPY %18(s32)
    PseudoRET implicit $x10, implicit $x11

...
