# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=riscv64 -run-pass=regbankselect -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV64I %s

--- |

  define void @add_anyext() { entry: ret void }
  define void @add_signext() { entry: ret void }
  define void @add_zeroext() { entry: ret void }

  ; Special case for i32 - single word operations are used.
  define void @add_i32() { entry: ret void }
  define void @sub_i32() { entry: ret void }
  define void @shl_i32() { entry: ret void }
  define void @ashr_i32() { entry: ret void }
  define void @lshr_i32() { entry: ret void }
  define void @mul_i32() { entry: ret void }
  define void @sdiv_i32() { entry: ret void }
  define void @srem_i32() { entry: ret void }
  define void @udiv_i32() { entry: ret void }
  define void @urem_i32() { entry: ret void }

  define void @add_i64() { entry: ret void }
  define void @sub_i64() { entry: ret void }
  define void @shl_i64() { entry: ret void }
  define void @ashr_i64() { entry: ret void }
  define void @lshr_i64() { entry: ret void }
  define void @and_i64() { entry: ret void }
  define void @or_i64() { entry: ret void }
  define void @xor_i64() { entry: ret void }
  define void @mul_i64() { entry: ret void }
  define void @sdiv_i64() { entry: ret void }
  define void @srem_i64() { entry: ret void }
  define void @udiv_i64() { entry: ret void }
  define void @urem_i64() { entry: ret void }

  ; Split operations.
  define void @add_i128() { entry: ret void }
  define void @sub_i128() { entry: ret void }
  define void @mul_i128() { entry: ret void }
...
---
name:            add_anyext
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_anyext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gprb(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gprb(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:gprb(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[ADD]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:_(s64) = COPY %0(s64)
    %7:_(s64) = COPY %2(s64)
    %8:_(s64) = G_ADD %6, %7
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_signext
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_signext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gprb(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gprb(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:gprb(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[ADD]](s64)
    ; RV64I: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 56
    ; RV64I: [[SHL:%[0-9]+]]:gprb(s64) = G_SHL [[COPY4]], [[C]](s64)
    ; RV64I: [[ASHR:%[0-9]+]]:gprb(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; RV64I: $x10 = COPY [[ASHR]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:_(s64) = COPY %0(s64)
    %7:_(s64) = COPY %2(s64)
    %8:_(s64) = G_ADD %6, %7
    %9:_(s64) = COPY %8(s64)
    %11:_(s64) = G_CONSTANT i64 56
    %10:_(s64) = G_SHL %9, %11(s64)
    %5:_(s64) = G_ASHR %10, %11(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_zeroext
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_zeroext
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gprb(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gprb(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADD:%[0-9]+]]:gprb(s64) = G_ADD [[COPY2]], [[COPY3]]
    ; RV64I: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 255
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[ADD]](s64)
    ; RV64I: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY4]], [[C]]
    ; RV64I: $x10 = COPY [[AND]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:_(s64) = COPY %0(s64)
    %7:_(s64) = COPY %2(s64)
    %8:_(s64) = G_ADD %6, %7
    %9:_(s64) = G_CONSTANT i64 255
    %10:_(s64) = COPY %8(s64)
    %5:_(s64) = G_AND %10, %9
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADDW:%[0-9]+]]:gpr(s64) = ADDW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[ADDW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = ADDW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            sub_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sub_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[SUBW:%[0-9]+]]:gpr(s64) = SUBW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[SUBW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = SUBW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            shl_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: shl_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[SLLW:%[0-9]+]]:gpr(s64) = SLLW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[SLLW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = SLLW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            ashr_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: ashr_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[SRAW:%[0-9]+]]:gpr(s64) = SRAW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[SRAW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = SRAW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            lshr_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: lshr_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[ADDW:%[0-9]+]]:gpr(s64) = ADDW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[ADDW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = ADDW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            mul_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: mul_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[MULW:%[0-9]+]]:gpr(s64) = MULW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[MULW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = MULW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            sdiv_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sdiv_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[DIVW:%[0-9]+]]:gpr(s64) = DIVW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[DIVW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = DIVW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            srem_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: srem_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[REMW:%[0-9]+]]:gpr(s64) = REMW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[REMW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = REMW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            udiv_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: udiv_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[DIVUW:%[0-9]+]]:gpr(s64) = DIVUW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[DIVUW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = DIVUW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            urem_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: urem_i32
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gpr(s64) = COPY [[COPY]](s64)
    ; RV64I: [[COPY3:%[0-9]+]]:gpr(s64) = COPY [[COPY1]](s64)
    ; RV64I: [[REMUW:%[0-9]+]]:gpr(s64) = REMUW [[COPY2]](s64), [[COPY3]](s64)
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[REMUW]](s64)
    ; RV64I: $x10 = COPY [[COPY4]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %2:_(s64) = COPY $x11
    %6:gpr(s64) = COPY %0(s64)
    %7:gpr(s64) = COPY %2(s64)
    %8:gpr(s64) = REMUW %6(s64), %7(s64)
    %5:_(s64) = COPY %8(s64)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            add_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: add_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[ADD:%[0-9]+]]:gprb(s64) = G_ADD [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[ADD]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_ADD %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            sub_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sub_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[SUB:%[0-9]+]]:gprb(s64) = G_SUB [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SUB]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SUB %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            shl_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: shl_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[SHL:%[0-9]+]]:gprb(s64) = G_SHL [[COPY]], [[COPY1]](s64)
    ; RV64I: $x10 = COPY [[SHL]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SHL %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            ashr_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: ashr_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[ASHR:%[0-9]+]]:gprb(s64) = G_ASHR [[COPY]], [[COPY1]](s64)
    ; RV64I: $x10 = COPY [[ASHR]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_ASHR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            lshr_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: lshr_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[LSHR:%[0-9]+]]:gprb(s64) = G_LSHR [[COPY]], [[COPY1]](s64)
    ; RV64I: $x10 = COPY [[LSHR]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_LSHR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            and_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: and_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[AND]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_AND %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            or_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: or_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[OR:%[0-9]+]]:gprb(s64) = G_OR [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[OR]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_OR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            xor_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: xor_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[XOR:%[0-9]+]]:gprb(s64) = G_XOR [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[XOR]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_XOR %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            mul_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: mul_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[MUL:%[0-9]+]]:gprb(s64) = G_MUL [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[MUL]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_MUL %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            sdiv_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: sdiv_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[SDIV:%[0-9]+]]:gprb(s64) = G_SDIV [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SDIV]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SDIV %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            srem_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: srem_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[SREM:%[0-9]+]]:gprb(s64) = G_SREM [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[SREM]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SREM %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            udiv_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: udiv_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[UDIV:%[0-9]+]]:gprb(s64) = G_UDIV [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[UDIV]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_UDIV %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            urem_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV64I-LABEL: name: urem_i64
    ; RV64I: liveins: $x10, $x11
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[UREM:%[0-9]+]]:gprb(s64) = G_UREM [[COPY]], [[COPY1]]
    ; RV64I: $x10 = COPY [[UREM]](s64)
    ; RV64I: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_UREM %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            add_i128
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: add_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gprb(s64) = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:gprb(s64) = COPY $x13
    ; RV64I: [[ADD:%[0-9]+]]:gprb(s64) = G_ADD [[COPY]], [[COPY2]]
    ; RV64I: [[ICMP:%[0-9]+]]:gprb(s64) = G_ICMP intpred(ult), [[ADD]](s64), [[COPY2]]
    ; RV64I: [[ADD1:%[0-9]+]]:gprb(s64) = G_ADD [[COPY1]], [[COPY3]]
    ; RV64I: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[ICMP]](s64)
    ; RV64I: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY4]], [[C]]
    ; RV64I: [[ADD2:%[0-9]+]]:gprb(s64) = G_ADD [[ADD1]], [[AND]]
    ; RV64I: $x10 = COPY [[ADD]](s64)
    ; RV64I: $x11 = COPY [[ADD2]](s64)
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = COPY $x12
    %3:_(s64) = COPY $x13
    %13:_(s64) = G_ADD %0, %2
    %19:_(s64) = G_ICMP intpred(ult), %13(s64), %2
    %17:_(s64) = G_ADD %1, %3
    %20:_(s64) = G_CONSTANT i64 1
    %21:_(s64) = COPY %19(s64)
    %18:_(s64) = G_AND %21, %20
    %15:_(s64) = G_ADD %17, %18
    $x10 = COPY %13(s64)
    $x11 = COPY %15(s64)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            sub_i128
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: sub_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gprb(s64) = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:gprb(s64) = COPY $x13
    ; RV64I: [[SUB:%[0-9]+]]:gprb(s64) = G_SUB [[COPY]], [[COPY2]]
    ; RV64I: [[ICMP:%[0-9]+]]:gprb(s64) = G_ICMP intpred(ult), [[COPY]](s64), [[COPY2]]
    ; RV64I: [[SUB1:%[0-9]+]]:gprb(s64) = G_SUB [[COPY1]], [[COPY3]]
    ; RV64I: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; RV64I: [[COPY4:%[0-9]+]]:gprb(s64) = COPY [[ICMP]](s64)
    ; RV64I: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY4]], [[C]]
    ; RV64I: [[SUB2:%[0-9]+]]:gprb(s64) = G_SUB [[SUB1]], [[AND]]
    ; RV64I: $x10 = COPY [[SUB]](s64)
    ; RV64I: $x11 = COPY [[SUB2]](s64)
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = COPY $x12
    %3:_(s64) = COPY $x13
    %13:_(s64) = G_SUB %0, %2
    %21:_(s64) = G_ICMP intpred(ult), %0(s64), %2
    %17:_(s64) = G_SUB %1, %3
    %22:_(s64) = G_CONSTANT i64 1
    %23:_(s64) = COPY %21(s64)
    %18:_(s64) = G_AND %23, %22
    %15:_(s64) = G_SUB %17, %18
    $x10 = COPY %13(s64)
    $x11 = COPY %15(s64)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            mul_i128
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13

    ; RV64I-LABEL: name: mul_i128
    ; RV64I: liveins: $x10, $x11, $x12, $x13
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I: [[COPY2:%[0-9]+]]:gprb(s64) = COPY $x12
    ; RV64I: [[COPY3:%[0-9]+]]:gprb(s64) = COPY $x13
    ; RV64I: [[MUL:%[0-9]+]]:gprb(s64) = G_MUL [[COPY]], [[COPY2]]
    ; RV64I: [[MUL1:%[0-9]+]]:gprb(s64) = G_MUL [[COPY1]], [[COPY2]]
    ; RV64I: [[MUL2:%[0-9]+]]:gprb(s64) = G_MUL [[COPY]], [[COPY3]]
    ; RV64I: [[UMULH:%[0-9]+]]:gprb(s64) = G_UMULH [[COPY]], [[COPY2]]
    ; RV64I: [[ADD:%[0-9]+]]:gprb(s64) = G_ADD [[MUL1]], [[MUL2]]
    ; RV64I: [[ADD1:%[0-9]+]]:gprb(s64) = G_ADD [[ADD]], [[UMULH]]
    ; RV64I: $x10 = COPY [[MUL]](s64)
    ; RV64I: $x11 = COPY [[ADD1]](s64)
    ; RV64I: PseudoRET implicit $x10, implicit $x11
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = COPY $x12
    %3:_(s64) = COPY $x13
    %13:_(s64) = G_MUL %0, %2
    %14:_(s64) = G_MUL %1, %2
    %15:_(s64) = G_MUL %0, %3
    %16:_(s64) = G_UMULH %0, %2
    %17:_(s64) = G_ADD %14, %15
    %18:_(s64) = G_ADD %17, %16
    $x10 = COPY %13(s64)
    $x11 = COPY %18(s64)
    PseudoRET implicit $x10, implicit $x11

...
